FROM python:3.12

ENV PYTHONUNBUFFERED 1

WORKDIR /code

COPY requirements.txt /code/
RUN pip install --upgrade pip setuptools wheel
RUN pip install --no-cache-dir -r requirements.txt

COPY . /code/

CMD ["celery", "-A", "bolbol", "worker", "-l", "INFO"]
