services:
  web:
    env_file:
      - ./local.env
    ports:
      - "8000:8000"
    volumes:
      - .:/code
      - ./static:/code/static
      - ./uploads:/code/uploads

  nginx:
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.local.conf:/etc/nginx/conf.d/default.conf:ro
      - ./static:/app/static
      - ./uploads:/app/uploads
