# Generated by Django 5.1.5 on 2025-01-28 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_user_product_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='main_category',
        ),
        migrations.AddField(
            model_name='category',
            name='super_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcategories', related_query_name='subcategory', to='products.category', verbose_name='Main category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.IntegerField(blank=True, null=True, verbose_name='Display order'),
        ),
    ]
