# Generated by Django 5.1.5 on 2025-01-28 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_category_main_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='extra_filters',
            new_name='characteristics',
        ),
    ]
