# Generated by Django 5.1.5 on 2025-01-30 22:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_rename_extra_filters_product_characteristics'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the complaint category.', max_length=100, verbose_name='Category Name')),
                ('description', models.TextField(blank=True, help_text='A brief description of the complaint category.', null=True, verbose_name='Description')),
                ('priority_level', models.CharField(choices=[('green', '🟢 Green (Low Priority)'), ('yellow', '🟡 Yellow (Medium Priority)'), ('red', '🔴 Red (High Priority)')], default='green', help_text='The priority level of this complaint category.', max_length=6, verbose_name='Priority Level')),
            ],
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-posted_at',), 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AddField(
            model_name='comment',
            name='masked_author_name',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name="Author's masked name"),
        ),
        migrations.AlterField(
            model_name='comment',
            name='posted_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Posted at'),
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Text')),
                ('complained_at', models.DateTimeField(auto_now_add=True, verbose_name='Complained at')),
                ('complainant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', related_query_name='complaint', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', related_query_name='complaint', to='products.product', verbose_name='Product')),
                ('category', models.ForeignKey(blank=True, help_text='The category of the complaint.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.complaintcategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Complaint',
                'verbose_name_plural': 'Complaints',
                'ordering': ('-complained_at',),
            },
        ),
    ]
