# Generated by Django 5.1.5 on 2025-01-30 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_complaintcategory_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='text',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Text'),
        ),
    ]
