# Generated by Django 5.1.5 on 2025-01-30 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_complaint_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaintcategory',
            options={'verbose_name': 'Complaint Category', 'verbose_name_plural': 'Complaint Categories'},
        ),
    ]
