# Generated by Django 5.1.5 on 2025-02-03 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_complaintcategory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productphoto',
            name='image',
            field=models.ImageField(upload_to='products/photos/%Y/%m/%d', verbose_name='Image'),
        ),
    ]
