# Generated by Django 5.1.6 on 2025-02-10 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_productphoto_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_super_chance',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Is super chance'),
        ),
    ]
