# Generated by Django 5.1.6 on 2025-02-12 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_product_is_super_chance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='view_count',
        ),
        migrations.AddField(
            model_name='product',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Views count'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_barter_enabled',
            field=models.BooleanField(default=True, verbose_name='Is barter option enabled'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_credit_enabled',
            field=models.BooleanField(default=True, verbose_name='Is credit option enabled'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_delivery_enabled',
            field=models.BooleanField(default=True, verbose_name='Is delivery option enabled'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_negotiator_enabled',
            field=models.BooleanField(default=True, verbose_name='Is negotiator option enabled'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_new_product_enabled',
            field=models.BooleanField(default=True, verbose_name='Is new product option enabled'),
        ),
        migrations.CreateModel(
            name='CategoryFilterField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='additional_fields', related_query_name='additional_field', to='products.category')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_filter_fields', related_query_name='category_filter_field', to='products.category')),
            ],
        ),
    ]
