# Generated by Django 5.1.6 on 2025-02-12 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_categoryfilterfield_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryfilterfield',
            name='is_autogenerating_product_name',
            field=models.BooleanField(default=False, verbose_name='Is autogenerating product name'),
        ),
    ]
