# Generated by Django 5.1.6 on 2025-02-12 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_categoryfilterfield_is_autogenerating_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryfilterfield',
            name='placeholder_text',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Placeholder text'),
        ),
    ]
