# Generated by Django 5.1.6 on 2025-02-12 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_categoryfilterfield_placeholder_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryfilterfield',
            name='tooltip_text',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Tooltip text'),
        ),
    ]
