# Generated by Django 5.1.6 on 2025-02-12 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_categoryfilterfield_tooltip_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryfilterfield',
            name='is_required',
            field=models.BooleanField(default=True, verbose_name='Is required'),
        ),
    ]
