# Generated by Django 5.1.6 on 2025-02-12 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_categoryfilterfield_is_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryfilterfield',
            name='parent_field',
            field=models.ForeignKey(blank=True, help_text='The parent field that determines when this field appears.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dependent_fields', to='products.categoryfilterfield', verbose_name='Parent Field'),
        ),
    ]
