# Generated by Django 5.1.6 on 2025-02-20 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_categoryfilterfield_parent_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='super_category',
            new_name='main_category',
        ),
    ]
