# Generated by Django 5.1.6 on 2025-02-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_delivery_available',
            field=models.BooleanField(default=False, verbose_name='Is delivery available'),
        ),
    ]
