# Generated by Django 5.1.6 on 2025-07-18 16:40

import django.core.validators
import django.db.models.deletion
import utils.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_alter_product_is_delivery_available'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, validators=[utils.validators.min_7_days_validator, utils.validators.max_30_days_validator], verbose_name='Expires at'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='unkown', max_length=255, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=255, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid “slug” consisting of letters, numbers, underscores, hyphens or Azerbaijani characters.', regex='^[a-zA-Z0-9əöşçğıüƏÖŞÇĞİÜ_-]+$')], verbose_name='Slug'),
        ),
        migrations.CreateModel(
            name='ProductUpdateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_data', models.JSONField(blank=True, null=True)),
                ('photo_meta', models.JSONField(blank=True, null=True)),
                ('data', models.JSONField()),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Rejected')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_requests', to='products.product')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product update request',
                'verbose_name_plural': 'Product update requests',
            },
        ),
        migrations.CreateModel(
            name='ReactivationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Rejected')], default=0, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_note', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactivation_requests', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reactivation request',
                'verbose_name_plural': 'Reactivation requests',
            },
        ),
    ]
