# Generated by Django 5.1.5 on 2025-01-25 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('slogan', models.CharField(blank=True, max_length=255, null=True, verbose_name='Slogan')),
                ('logo', models.ImageField(blank=True, max_length=255, null=True, upload_to='shops/logos/%Y/%m/%d', verbose_name='Logo')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('intro_text', models.TextField(blank=True, null=True, verbose_name='Intro text')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='shops/background/%Y/%m/%d', verbose_name='Background image')),
                ('map_link', models.URLField(blank=True, null=True, verbose_name='Map location link')),
                ('map_latitude', models.FloatField(blank=True, null=True, verbose_name='Map location latitude')),
                ('map_longitude', models.FloatField(blank=True, null=True, verbose_name='Map location longitude')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Shop',
                'verbose_name_plural': 'Shops',
            },
        ),
        migrations.CreateModel(
            name='ShopRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slogan', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_requests', related_query_name='shop_request', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shop request',
                'verbose_name_plural': 'Shop requests',
            },
        ),
    ]
