# Generated by Django 5.1.6 on 2025-07-21 15:02

import django.db.models.deletion
import utils.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='partners/logos', verbose_name='Logo')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('url', models.URLField(max_length=255, verbose_name='Company URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Partner company',
                'verbose_name_plural': 'Partner companies',
            },
        ),
        migrations.CreateModel(
            name='ShopActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
            ],
            options={
                'verbose_name': 'Shop Activity',
                'verbose_name_plural': 'Shop Activities',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('logo', models.ImageField(blank=True, max_length=255, null=True, upload_to='shops/logos/%Y/%m/%d', verbose_name='Logo')),
                ('address', models.TextField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Intro text')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='shops/background/%Y/%m/%d', verbose_name='Background image')),
                ('map_link', models.URLField(blank=True, max_length=255, null=True, verbose_name='Map location link')),
                ('map_latitude', models.FloatField(blank=True, null=True, verbose_name='Map location latitude')),
                ('map_longitude', models.FloatField(blank=True, null=True, verbose_name='Map location longitude')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('shop_working_hours_data', models.JSONField(blank=True, default=dict, null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shops', related_query_name='shop', to='products.city', verbose_name='City')),
                ('owner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('activities', models.ManyToManyField(to='shops.shopactivity', verbose_name='Shop Activities')),
            ],
            options={
                'verbose_name': 'Shop',
                'verbose_name_plural': 'Shops',
            },
        ),
        migrations.CreateModel(
            name='ShopContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True, validators=[utils.validators.validate_phone_number], verbose_name='Phone number')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', related_query_name='contact', to='shops.shop', verbose_name='Shop')),
            ],
            options={
                'verbose_name': 'Shop contact',
                'verbose_name_plural': 'Shop contacts',
            },
        ),
        migrations.CreateModel(
            name='ShopRegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_owner_full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('shop_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Shop Name')),
                ('status', models.CharField(choices=[('in_review', 'In Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='in_review', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop_activities', models.ManyToManyField(to='shops.shopactivity', verbose_name='Shop Activities')),
                ('shop_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_requests', related_query_name='shop_request', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shop Registration Request',
                'verbose_name_plural': 'Shop Registration Requests',
            },
        ),
        migrations.CreateModel(
            name='ShopWorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=9, null=True)),
                ('opening_time', models.TimeField(blank=True, null=True, verbose_name='Opening Time')),
                ('closing_time', models.TimeField(blank=True, null=True, verbose_name='Closing Time')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', related_query_name='working_hour', to='shops.shop', verbose_name='Shop')),
            ],
            options={
                'unique_together': {('shop', 'day_of_week')},
            },
        ),
    ]
