# Generated by Django 5.1.5 on 2025-01-26 21:24

import django.db.models.deletion
import utils.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Shop Activity',
                'verbose_name_plural': 'Shop Activities',
            },
        ),
        migrations.RenameModel(
            old_name='ShopRequest',
            new_name='ShopRegistrationRequest',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='intro_text',
            new_name='bio',
        ),
        migrations.AlterField(
            model_name='shop',
            name='address',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='map_link',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Map location link'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='shop',
            name='activities',
            field=models.ManyToManyField(to='shops.shopactivity', verbose_name='Shop Activities'),
        ),
        migrations.CreateModel(
            name='ShopContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True, validators=[utils.validators.validate_phone_number], verbose_name='Phone number')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', related_query_name='contact', to='shops.shop', verbose_name='Shop')),
            ],
            options={
                'verbose_name': 'Shop contact',
                'verbose_name_plural': 'Shop contacts',
            },
        ),
        migrations.CreateModel(
            name='ShopWorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=9, null=True)),
                ('opening_time', models.TimeField(blank=True, null=True, verbose_name='Opening Time')),
                ('closing_time', models.TimeField(blank=True, null=True, verbose_name='Closing Time')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', related_query_name='working_hour', to='shops.shop', verbose_name='Shop')),
            ],
            options={
                'unique_together': {('shop', 'day_of_week')},
            },
        ),
    ]
