# Generated by Django 5.1.5 on 2025-01-26 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_shopactivity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopregistrationrequest',
            options={'verbose_name': 'Shop Registration Request', 'verbose_name_plural': 'Shop Registration Requests'},
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='shopregistrationrequest',
            old_name='owner',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='shopregistrationrequest',
            name='name',
        ),
        migrations.RemoveField(
            model_name='shopregistrationrequest',
            name='slogan',
        ),
        migrations.AddField(
            model_name='shopregistrationrequest',
            name='shop_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Shop Name'),
        ),
        migrations.AlterField(
            model_name='shopregistrationrequest',
            name='description',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Description'),
        ),
    ]
