# Generated by Django 5.1.5 on 2025-01-26 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_alter_shopregistrationrequest_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopregistrationrequest',
            name='description',
        ),
        migrations.AddField(
            model_name='shopregistrationrequest',
            name='activities',
            field=models.ManyToManyField(to='shops.shopactivity', verbose_name='Shop Activities'),
        ),
        migrations.AddField(
            model_name='shopregistrationrequest',
            name='status',
            field=models.CharField(choices=[('in_review', 'In Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='in_review', max_length=10, verbose_name='Status'),
        ),
    ]
