# Generated by Django 5.1.5 on 2025-01-26 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_remove_shopregistrationrequest_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopregistrationrequest',
            old_name='activities',
            new_name='shop_activities',
        ),
    ]
