# Generated by Django 5.1.5 on 2025-01-26 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_rename_activities_shopregistrationrequest_shop_activities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopactivity',
            name='description',
        ),
    ]
