# Generated by Django 5.1.5 on 2025-01-26 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0006_remove_shopactivity_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopactivity',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
