# Generated by Django 5.1.5 on 2025-01-26 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0007_shopactivity_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopactivity',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active'),
        ),
    ]
