# Generated by Django 5.1.6 on 2025-02-10 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0008_alter_shopactivity_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopregistrationrequest',
            old_name='user',
            new_name='shop_owner',
        ),
    ]
