# Generated by Django 5.1.6 on 2025-02-10 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0009_rename_user_shopregistrationrequest_shop_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shopregistrationrequest',
            name='shop_owner_full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shopregistrationrequest',
            name='shop_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_requests', related_query_name='shop_request', to=settings.AUTH_USER_MODEL),
        ),
    ]
