# Generated by Django 5.1.6 on 2025-03-05 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_alter_product_is_delivery_available'),
        ('shops', '0010_shopregistrationrequest_shop_owner_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='slogan',
        ),
        migrations.AddField(
            model_name='shop',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shops', related_query_name='shop', to='products.city', verbose_name='City'),
        ),
    ]
