# Generated by Django 5.1.6 on 2025-03-14 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0011_remove_shop_slogan_shop_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='shop_working_hours_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
